// Signal codes, weights, severities and default thresholds per SPEC section 7.

const DEFAULT_WEIGHTS = {
  KNOWN_FINGERPRINT: 10,
  EXTENSION_IFRAME: 8,
  FIXED_HIGH_Z_NODE: 5,
  FOREIGN_SHADOW_ROOT: 4,
  DOM_NODE_DELTA: 2,
  WINDOW_BLUR: 1,
  TAB_HIDDEN: 2,
  TAB_VISIBLE: 1,
  PASTE_EVENT: 1,
  FULLSCREEN_EXIT: 1,
  DEVTOOLS_OPEN: 2,
  BROWSER_TAB_SWITCH: 1,
};

const DEFAULT_SEVERITY = {
  KNOWN_FINGERPRINT: 'HIGH',
  EXTENSION_IFRAME: 'HIGH',
  FIXED_HIGH_Z_NODE: 'MED',
  FOREIGN_SHADOW_ROOT: 'MED',
  DOM_NODE_DELTA: 'LOW',
  WINDOW_BLUR: 'LOW',
  TAB_HIDDEN: 'LOW',
  TAB_VISIBLE: 'LOW',
  PASTE_EVENT: 'LOW',
  FULLSCREEN_EXIT: 'LOW',
  DEVTOOLS_OPEN: 'LOW',
  BROWSER_TAB_SWITCH: 'LOW',
};

const DEFAULT_THRESHOLDS = {
  LOW: { windowMs: 60000, flagScore: 15 },
  MEDIUM: { windowMs: 60000, flagScore: 8 },
  HIGH: { windowMs: 60000, flagScore: 4 },
};

const SEVERITY_RANK = {
  NONE: 0,
  LOW: 1,
  MED: 2,
  HIGH: 3,
};

module.exports = {
  DEFAULT_WEIGHTS,
  DEFAULT_SEVERITY,
  DEFAULT_THRESHOLDS,
  SEVERITY_RANK,
};
